on: [push]

jobs:
  check:
    name: py${{ matrix.python }} pillow-${{ matrix.pillow }} libheif-${{ matrix.libheif }} pyheif-${{ matrix.pyheif }}
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    strategy:
      matrix:
        python: ['3.8', '3.11']
        pillow: [prod, latest]
        libheif: ['1.16.2-6ee6762-3f6b709', '1.18.2-bf35e9e-47f4fc0']
        pyheif: ['', '0.7.1']
        exclude:
          - python: '3.11'
            pyheif: '0.7.1'
          - libheif: '1.18.2-bf35e9e-47f4fc0'
            pyheif: '0.7.1'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install system dependencies
      run: |
        BUCKET=https://uploadcare-packages.s3.amazonaws.com
        curl -fLO $BUCKET/libheif/libheif-uc_${{ matrix.libheif }}_$(dpkg --print-architecture).deb
        sudo dpkg -i *.deb && rm *.deb
        sudo apt install --no-install-recommends -y libjpeg-dev
    - name: Update pip
      run: pip install pip==23.2.1
    - name: Install dependencies
      run: make install-pillow-${{ matrix.pillow }}
    - name: Install ovsolete pyheif
      if: ${{ matrix.pyheif }}
      run: |
        pip uninstall -y pyheif
        pip install pyheif==${{ matrix.pyheif }}
    - name: Check
      run: make check
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
