on: [push]

jobs:
  check:
    name: py${{ matrix.python }} pillow-${{ matrix.pillow }} pyheif-${{ matrix.pyheif }}
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    strategy:
      matrix:
        python: ['3.8', '3.11']
        pillow: [prod, latest]
        pyheif: [prod, latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install system dependencies
      run: |
        BUCKET=https://uploadcare-packages.s3.amazonaws.com
        curl -fLO $BUCKET/libheif/libheif-uc_1.18.2-bf35e9e-47f4fc0_$(dpkg --print-architecture).deb
        sudo dpkg -i *.deb && rm *.deb
        sudo apt install --no-install-recommends -y libjpeg-dev
    - name: Update pip
      run: pip install pip==23.2.1
    - name: Install dependencies
      run: make install-pyheif-${{ matrix.pyheif }}-pillow-${{ matrix.pillow }}
    - name: Check
      run: make check
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        verbose: true
