on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v7

    - name: Install dependencies
      run: |
        pip install --upgrade 'pip>=25.1'
        pip install --group dev

    - name: Lint
      run: make lint
